version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ejs
    versions:
    - 3.1.6
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: ini
    versions:
    - 1.3.8
